amap:
    resource: "@AmapBundle/Resources/config/routing.xml"
    prefix:   /

amap:
    resource: "@AmapBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
