amap_responsable:
    resource: "@AmapBundle/Resources/config/routing/responsable.xml"
    prefix:   /responsable

amap_amap:
    resource: "@AmapBundle/Resources/config/routing/amap.xml"
    prefix:   /amap

<<<<<<< HEAD
amap_responsable:
    resource: "@AmapBundle/Resources/config/routing/responsable.xml"
    prefix:   /responsable

amap_amap:
    resource: "@AmapBundle/Resources/config/routing/amap.xml"
    prefix:   /amap
=======
amap_preferenceConsommateur:
    resource: "@AmapBundle/Resources/config/routing/preferenceconsommateur.xml"
    prefix:   /preferenceConsommateur
>>>>>>> 829dee79caede16be16f95bc6a67f11c9ca63338

