amap_responsable:
    resource: "@AmapBundle/Resources/config/routing/responsable.xml"
    prefix:   /responsable

amap_amap:
    resource: "@AmapBundle/Resources/config/routing/amap.xml"
    prefix:   /amap

