amap_contratProducteur:
    resource: "@AmapBundle/Resources/config/routing/contratproducteur.xml"
    prefix:   /contratProducteur

amap_contratconsommateur:
    resource: "@AmapBundle/Resources/config/routing/contratconsommateur.xml"
    prefix:   /contratconsommateur

amap_magasin:
    resource: "@AmapBundle/Resources/config/routing/magasin.xml"
    prefix:   /magasin

amap_saison:
    resource: "@AmapBundle/Resources/config/routing/saison.xml"
    prefix:   /saison

